<?php

use App\Events\TestBroadcastEvent;
use App\Jobs\ProcessDailyKeywordRanksJob;
use App\Jobs\TestJob;
use App\Models\Keyword;
use Illuminate\Support\Facades\Route;


// 🔊 Test broadcasting with Soketi
Route::get('/broadcast-test', function () {
    broadcast(new TestBroadcastEvent('Hello from Laravel + Soketi!'));
    return 'Event broadcasted!';
});

// 🚀 Job trigger: Daily keyword rank processing
Route::get('/run-keyword-job', function () {
    ProcessDailyKeywordRanksJob::dispatch();

    return response()->json([
        'message' => '✅ Keyword rank job dispatched successfully!',
    ]);
});

// 🧪 Job trigger: Simple test job
Route::get('/run-test-job', function () {
    TestJob::dispatch();

    return response()->json([
        'message' => '✅ TestJob dispatched successfully!',
    ]);
});


Route::get('/test', function () {


    $url = "https://growmemarketing.ca/";
    $seoResults = [
        [
            "type" => "organic",
            "rank_group" => "1",
            "rank_absolute" => "1",
            "domain" => "classifieds.calgaryherald.com",
            "title" => "Calgary Herald | Classifieds",
            "description" => "Free and paid All classified ads of the Calgary Herald Classifieds. Browse All classified ads and free ads. Post free All classified ads.",
            "url" => "https://classifieds.calgaryherald.com/",
            "breadcrumb" => "https://classifieds.calgaryherald.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "2",
            "rank_absolute" => "2",
            "domain" => "calgary.craigslist.org",
            "title" => "craigslist: calgary jobs, apartments, for sale, services ...",
            "description" => "craigslist provides local classifieds and forums for jobs, housing, for sale, services, local community, and events.",
            "url" => "https://calgary.craigslist.org/",
            "breadcrumb" => "https://calgary.craigslist.org",
        ],
        [
            "type" => "organic",
            "rank_group" => "3",
            "rank_absolute" => "3",
            "domain" => "www.pattisonoutdoor.com",
            "title" => "Calgary - Pattison Outdoor",
            "description" => "PATTISON offers the most monumental form of advertising in Calgary. Classic, Digital, Transit and Place Based advertising bring its own unique value to your ...",
            "url" => "https://www.pattisonoutdoor.com/market-location/calgary/",
            "breadcrumb" => "https://www.pattisonoutdoor.com › market-location › c...",
        ],
        [
            "type" => "organic",
            "rank_group" => "4",
            "rank_absolute" => "4",
            "domain" => "example3.com",
            "title" => "Sample Title 3",
            "description" => "Sample description for entry 3.",
            "url" => "https://example3.com/",
            "breadcrumb" => "https://example3.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "5",
            "rank_absolute" => "5",
            "domain" => "example4.com",
            "title" => "Sample Title 4",
            "description" => "Sample description for entry 4.",
            "url" => "https://example4.com/",
            "breadcrumb" => "https://example4.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "6",
            "rank_absolute" => "6",
            "domain" => "example5.com",
            "title" => "Sample Title 5",
            "description" => "Sample description for entry 5.",
            "url" => "https://example5.com/",
            "breadcrumb" => "https://example5.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "7",
            "rank_absolute" => "7",
            "domain" => "example6.com",
            "title" => "Sample Title 6",
            "description" => "Sample description for entry 6.",
            "url" => "https://example6.com/",
            "breadcrumb" => "https://example6.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "8",
            "rank_absolute" => "8",
            "domain" => "example7.com",
            "title" => "Sample Title 7",
            "description" => "Sample description for entry 7.",
            "url" => "https://example7.com/",
            "breadcrumb" => "https://example7.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "9",
            "rank_absolute" => "9",
            "domain" => "example8.com",
            "title" => "Sample Title 8",
            "description" => "Sample description for entry 8.",
            "url" => "https://example8.com/",
            "breadcrumb" => "https://example8.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "10",
            "rank_absolute" => "10",
            "domain" => "example9.com",
            "title" => "Sample Title 9",
            "description" => "Sample description for entry 9.",
            "url" => "https://example9.com/",
            "breadcrumb" => "https://example9.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "11",
            "rank_absolute" => "11",
            "domain" => "example10.com",
            "title" => "Sample Title 10",
            "description" => "Sample description for entry 10.",
            "url" => "https://example10.com/",
            "breadcrumb" => "https://example10.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "12",
            "rank_absolute" => "12",
            "domain" => "example11.com",
            "title" => "Sample Title 11",
            "description" => "Sample description for entry 11.",
            "url" => "https://example11.com/",
            "breadcrumb" => "https://example11.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "13",
            "rank_absolute" => "13",
            "domain" => "example12.com",
            "title" => "Sample Title 12",
            "description" => "Sample description for entry 12.",
            "url" => "https://example12.com/",
            "breadcrumb" => "https://example12.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "14",
            "rank_absolute" => "14",
            "domain" => "example13.com",
            "title" => "Sample Title 13",
            "description" => "Sample description for entry 13.",
            "url" => "https://example13.com/",
            "breadcrumb" => "https://example13.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "15",
            "rank_absolute" => "15",
            "domain" => "example14.com",
            "title" => "Sample Title 14",
            "description" => "Sample description for entry 14.",
            "url" => "https://example14.com/",
            "breadcrumb" => "https://example14.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "16",
            "rank_absolute" => "16",
            "domain" => "example15.com",
            "title" => "Sample Title 15",
            "description" => "Sample description for entry 15.",
            "url" => "https://example15.com/",
            "breadcrumb" => "https://example15.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "17",
            "rank_absolute" => "17",
            "domain" => "example16.com",
            "title" => "Sample Title 16",
            "description" => "Sample description for entry 16.",
            "url" => "https://example16.com/",
            "breadcrumb" => "https://example16.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "18",
            "rank_absolute" => "18",
            "domain" => "example17.com",
            "title" => "Sample Title 17",
            "description" => "Sample description for entry 17.",
            "url" => "https://example17.com/",
            "breadcrumb" => "https://example17.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "19",
            "rank_absolute" => "19",
            "domain" => "example18.com",
            "title" => "Sample Title 18",
            "description" => "Sample description for entry 18.",
            "url" => "https://example18.com/",
            "breadcrumb" => "https://example18.com",
        ],


        [
            "type" => "organic",
            "rank_group" => "58",
            "rank_absolute" => "58",
            "domain" => "example57.com",
            "title" => "Sample Title 57",
            "description" => "Sample description for entry 57.",
            "url" => "https://example57.com/",
            "breadcrumb" => "https://example57.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "59",
            "rank_absolute" => "59",
            "domain" => "example58.com",
            "title" => "Sample Title 58",
            "description" => "Sample description for entry 58.",
            "url" => "https://example58.com/",
            "breadcrumb" => "https://example58.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "60",
            "rank_absolute" => "60",
            "domain" => "example59.com",
            "title" => "Sample Title 59",
            "description" => "Sample description for entry 59.",
            "url" => "https://example59.com/",
            "breadcrumb" => "https://example59.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "61",
            "rank_absolute" => "61",
            "domain" => "example60.com",
            "title" => "Sample Title 60",
            "description" => "Sample description for entry 60.",
            "url" => "https://example60.com/",
            "breadcrumb" => "https://example60.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "62",
            "rank_absolute" => "62",
            "domain" => "example61.com",
            "title" => "Sample Title 61",
            "description" => "Sample description for entry 61.",
            "url" => "https://example61.com/",
            "breadcrumb" => "https://example61.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "63",
            "rank_absolute" => "63",
            "domain" => "example62.com",
            "title" => "Sample Title 62",
            "description" => "Sample description for entry 62.",
            "url" => "https://example62.com/",
            "breadcrumb" => "https://example62.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "64",
            "rank_absolute" => "64",
            "domain" => "example63.com",
            "title" => "Sample Title 63",
            "description" => "Sample description for entry 63.",
            "url" => "https://example63.com/",
            "breadcrumb" => "https://example63.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "65",
            "rank_absolute" => "65",
            "domain" => "example64.com",
            "title" => "Sample Title 64",
            "description" => "Sample description for entry 64.",
            "url" => "https://example64.com/",
            "breadcrumb" => "https://example64.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "66",
            "rank_absolute" => "66",
            "domain" => "example65.com",
            "title" => "Sample Title 65",
            "description" => "Sample description for entry 65.",
            "url" => "https://example65.com/",
            "breadcrumb" => "https://example65.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "67",
            "rank_absolute" => "67",
            "domain" => "example66.com",
            "title" => "Sample Title 66",
            "description" => "Sample description for entry 66.",
            "url" => "https://example66.com/",
            "breadcrumb" => "https://example66.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "68",
            "rank_absolute" => "68",
            "domain" => "example67.com",
            "title" => "Sample Title 67",
            "description" => "Sample description for entry 67.",
            "url" => "https://example67.com/",
            "breadcrumb" => "https://example67.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "69",
            "rank_absolute" => "69",
            "domain" => "example68.com",
            "title" => "Sample Title 68",
            "description" => "Sample description for entry 68.",
            "url" => "https://example68.com/",
            "breadcrumb" => "https://example68.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "70",
            "rank_absolute" => "70",
            "domain" => "example69.com",
            "title" => "Sample Title 69",
            "description" => "Sample description for entry 69.",
            "url" => "https://example69.com/",
            "breadcrumb" => "https://example69.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "71",
            "rank_absolute" => "71",
            "domain" => "example70.com",
            "title" => "Sample Title 70",
            "description" => "Sample description for entry 70.",
            "url" => "https://example70.com/",
            "breadcrumb" => "https://example70.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "72",
            "rank_absolute" => "72",
            "domain" => "example71.com",
            "title" => "Sample Title 71",
            "description" => "Sample description for entry 71.",
            "url" => "https://example71.com/",
            "breadcrumb" => "https://example71.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "73",
            "rank_absolute" => "73",
            "domain" => "example72.com",
            "title" => "Sample Title 72",
            "description" => "Sample description for entry 72.",
            "url" => "https://example72.com/",
            "breadcrumb" => "https://example72.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "74",
            "rank_absolute" => "74",
            "domain" => "example73.com",
            "title" => "Sample Title 73",
            "description" => "Sample description for entry 73.",
            "url" => "https://example73.com/",
            "breadcrumb" => "https://example73.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "75",
            "rank_absolute" => "75",
            "domain" => "example74.com",
            "title" => "Sample Title 74",
            "description" => "Sample description for entry 74.",
            "url" => "https://example74.com/",
            "breadcrumb" => "https://example74.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "76",
            "rank_absolute" => "76",
            "domain" => "example75.com",
            "title" => "Sample Title 75",
            "description" => "Sample description for entry 75.",
            "url" => "https://example75.com/",
            "breadcrumb" => "https://example75.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "77",
            "rank_absolute" => "77",
            "domain" => "example76.com",
            "title" => "Sample Title 76",
            "description" => "Sample description for entry 76.",
            "url" => "https://example76.com/",
            "breadcrumb" => "https://example76.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "78",
            "rank_absolute" => "78",
            "domain" => "example77.com",
            "title" => "Sample Title 77",
            "description" => "Sample description for entry 77.",
            "url" => "https://example77.com/",
            "breadcrumb" => "https://example77.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "79",
            "rank_absolute" => "79",
            "domain" => "example78.com",
            "title" => "Sample Title 78",
            "description" => "Sample description for entry 78.",
            "url" => "https://example78.com/",
            "breadcrumb" => "https://example78.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "80",
            "rank_absolute" => "80",
            "domain" => "example79.com",
            "title" => "Sample Title 79",
            "description" => "Sample description for entry 79.",
            "url" => "https://example79.com/",
            "breadcrumb" => "https://example79.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "81",
            "rank_absolute" => "81",
            "domain" => "example80.com",
            "title" => "Sample Title 80",
            "description" => "Sample description for entry 80.",
            "url" => "https://example80.com/",
            "breadcrumb" => "https://example80.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "82",
            "rank_absolute" => "82",
            "domain" => "example81.com",
            "title" => "Sample Title 81",
            "description" => "Sample description for entry 81.",
            "url" => "https://example81.com/",
            "breadcrumb" => "https://example81.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "83",
            "rank_absolute" => "83",
            "domain" => "example82.com",
            "title" => "Sample Title 82",
            "description" => "Sample description for entry 82.",
            "url" => "https://example82.com/",
            "breadcrumb" => "https://example82.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "84",
            "rank_absolute" => "84",
            "domain" => "example83.com",
            "title" => "Sample Title 83",
            "description" => "Sample description for entry 83.",
            "url" => "https://example83.com/",
            "breadcrumb" => "https://example83.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "85",
            "rank_absolute" => "85",
            "domain" => "example84.com",
            "title" => "Sample Title 84",
            "description" => "Sample description for entry 84.",
            "url" => "https://example84.com/",
            "breadcrumb" => "https://example84.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "86",
            "rank_absolute" => "86",
            "domain" => "example85.com",
            "title" => "Sample Title 85",
            "description" => "Sample description for entry 85.",
            "url" => "https://example85.com/",
            "breadcrumb" => "https://example85.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "87",
            "rank_absolute" => "87",
            "domain" => "example86.com",
            "title" => "Sample Title 86",
            "description" => "Sample description for entry 86.",
            "url" => "https://example86.com/",
            "breadcrumb" => "https://example86.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "88",
            "rank_absolute" => "88",
            "domain" => "example87.com",
            "title" => "Sample Title 87",
            "description" => "Sample description for entry 87.",
            "url" => "https://example87.com/",
            "breadcrumb" => "https://example87.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "89",
            "rank_absolute" => "89",
            "domain" => "example88.com",
            "title" => "Sample Title 88",
            "description" => "Sample description for entry 88.",
            "url" => "https://example88.com/",
            "breadcrumb" => "https://example88.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "90",
            "rank_absolute" => "90",
            "domain" => "example89.com",
            "title" => "Sample Title 89",
            "description" => "Sample description for entry 89.",
            "url" => "https://example89.com/",
            "breadcrumb" => "https://example89.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "91",
            "rank_absolute" => "91",
            "domain" => "example90.com",
            "title" => "Sample Title 90",
            "description" => "Sample description for entry 90.",
            "url" => "https://example90.com/",
            "breadcrumb" => "https://example90.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "92",
            "rank_absolute" => "92",
            "domain" => "example91.com",
            "title" => "Sample Title 91",
            "description" => "Sample description for entry 91.",
            "url" => "https://example91.com/",
            "breadcrumb" => "https://example91.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "93",
            "rank_absolute" => "93",
            "domain" => "example92.com",
            "title" => "Sample Title 92",
            "description" => "Sample description for entry 92.",
            "url" => "https://example92.com/",
            "breadcrumb" => "https://example92.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "94",
            "rank_absolute" => "94",
            "domain" => "example93.com",
            "title" => "Sample Title 93",
            "description" => "Sample description for entry 93.",
            "url" => "https://example93.com/",
            "breadcrumb" => "https://example93.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "95",
            "rank_absolute" => "95",
            "domain" => "example94.com",
            "title" => "Sample Title 94",
            "description" => "Sample description for entry 94.",
            "url" => "https://example94.com/",
            "breadcrumb" => "https://example94.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "96",
            "rank_absolute" => "96",
            "domain" => "example95.com",
            "title" => "Sample Title 95",
            "description" => "Sample description for entry 95.",
            "url" => "https://example95.com/",
            "breadcrumb" => "https://example95.com",
        ],
        [
            "type" => "organic",
            "rank_group" => "97",
            "rank_absolute" => "97",
            "domain" => "example96.com",
            "title" => "Sample Title 96",
            "description" => "Sample description for entry 96.",
            "url" => "https://example96.com/",
            "breadcrumb" => "https://example96.com",
        ],
    ];

     $rr =   filterDataForSeoItemsByHost($seoResults, $url);
     dd($rr);
});
