services:
  nginx:
    image: 'nginx:stable-alpine'
    ports:
      - "8000:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "../laravel:/var/www/laravel"
    depends_on:
      - mysql
      - php
  php:
    build:
      context: "./dockerfiles"
      dockerfile: "php.Dockerfile"
    volumes:
      - "../laravel:/var/www/laravel"
  mysql:
    image: mysql:8.2.0
    ports:
      - "3316:3306"
    env_file:
      - "env/mysql.env"
    volumes:
      - "../laravel:/var/www/laravel"
  composer:
    build:
      context: "./dockerfiles"
      dockerfile: "composer.Dockerfile"
    volumes:
      - "../laravel:/var/www/laravel"
  artisan:
    build:
      context: "./dockerfiles"
      dockerfile: "composer.Dockerfile"
    volumes:
      - "../laravel:/var/www/laravel"
    entrypoint: [ "php", "/var/www/laravel/artisan" ]
volumes:
  db_data: